# Generated by Django 6.0.2 on 2026-10-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_promotionalcreditclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('promotion', 'Promotional Credit')], max_length=50),
        ),
    ]
