# Generated by Django 6.0.2 on 2026-02-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
